language: node_js

services:
  - docker

cache:
  directories:
    - node_modules

node_js:
  - '6'
  - '4'

before_install:
  - npm i -g npm@5.3.0

install:
  - make vendor

script:
  - make test

before_deploy:
  - npm run lerna bootstrap
  - npm run lerna exec -- npm pack
  - sudo pip install awscli
  - aws configure set preview.cloudfront true

deploy:
  - provider: releases
    api-key: "$GITHUB_RELEASE_TOKEN"
    file:
      - "skygear-*.tgz"
    skip_cleanup: true
    file_glob: true
    on:
      repo: SkygearIO/skygear-SDK-JS
      tags: true
      node_js: 6
  - provider: script
    script: scripts/deploy-example.sh
    skip_cleanup: true
    on:
      branch: master
      node_js: 6
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      repo: SkygearIO/skygear-SDK-JS
      all_branches: true
      node_js: 6

notifications:
  slack:
    secure: "KXq/5P62jVCP7/EWVq1XFeHwIiMJgRdzm07ihvu9TXH0m9KDU6gnYVYrhAUfDVJ9SakN7JdgrJrheGPwDeypcfCVUAuaoMfI/FitBol8cIVlrkuAW/ybNWk2htuDLNeI3bPq1XKUzCiH8nurp6FvPFEGo1Vn2/3hVFYhfKRnoZKRZ3jsnHAEqdEaEsqaK/fjBK5Jh0ywYv2wzHQ2MQgaUIGsRUR/KKHvi8mxB8HBQCdHfVIFTwp4MiBvAoGpwfGuTyE8VOnbyOtRSUFCj2Iu0obVwhISoqku1SMnj7lIjt3mIhkXYuzdqT484iinw8UKijYEwOoV+iODVBOn4dw1zoUCWmkPnaq7xpWOpssj8EQJHl+6qzKxiY+7CCeQqxrR/fSyIS7Wem1VwmFXpzHfXg5wh5L28ETmu9WfjhDLmJTNhTzrhPHSVLXFJl2BAqT4cD+swGV/hhcS0bP5h4F0OxT7AkK9ehufDfPcoIbukvlX6y3okGomPznvgF0xCLWOWJZkzKokwEiixB8UqhHX2dMk81HwSmyIYTNyLVvsWR3C6qAqqfJjczsJVlAomj1kUljzPjM8J+gcd1euIlhcb/8kJbmbp+quX6DoEl7FSQvRMvUgSU3Omp1ak06j+OM0hy12ReI/m1uwFsoe6hyWTZXj+pCPQX027oLgNwdk628="
